version: "1"
services:
  # Node.js server
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql
    command: >
      bash -c "yarn && ./wait-for-it.sh mysql:3306 -- yarn prisma migrate reset --force && yarn start"

  # MySQL database
  mysql:
    image: mysql:latest
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
