version: '3'
services:
  # Node.js server
  node-app:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mysql

  # MySQL database
  mysql:
    image: mysql:latest
    container_name: mysql-db
    env_file:
      - .env
    ports:
      - "3306:3306"
